// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GetThingRequest
	GetThingResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GetThingRequest struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetThingRequest) Reset()                    { *m = GetThingRequest{} }
func (m *GetThingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetThingRequest) ProtoMessage()               {}
func (*GetThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetThingRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type GetThingResponse struct {
	Things           []int32 `protobuf:"varint,1,rep,name=things" json:"things,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetThingResponse) Reset()                    { *m = GetThingResponse{} }
func (m *GetThingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetThingResponse) ProtoMessage()               {}
func (*GetThingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetThingResponse) GetThings() []int32 {
	if m != nil {
		return m.Things
	}
	return nil
}

func init() {
	proto.RegisterType((*GetThingRequest)(nil), "protoapi.api.GetThingRequest")
	proto.RegisterType((*GetThingResponse)(nil), "protoapi.api.GetThingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for ThingService service

type ThingServiceClient interface {
	GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error)
}

type thingServiceClient struct {
	cc *grpc.ClientConn
}

func NewThingServiceClient(cc *grpc.ClientConn) ThingServiceClient {
	return &thingServiceClient{cc}
}

func (c *thingServiceClient) GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error) {
	out := new(GetThingResponse)
	err := grpc.Invoke(ctx, "/protoapi.api.ThingService/GetThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ThingService service

type ThingServiceServer interface {
	GetThing(context.Context, *GetThingRequest) (*GetThingResponse, error)
}

func RegisterThingServiceServer(s *grpc.Server, srv ThingServiceServer) {
	s.RegisterService(&_ThingService_serviceDesc, srv)
}

func _ThingService_GetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ThingServiceServer).GetThing(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _ThingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoapi.api.ThingService",
	HandlerType: (*ThingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThing",
			Handler:    _ThingService_GetThing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x53, 0x20, 0x3e, 0x10, 0x2b, 0x29, 0x72, 0xf1,
	0xbb, 0xa7, 0x96, 0x84, 0x64, 0x64, 0xe6, 0xa5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x01, 0x59, 0x4a, 0x5a,
	0x5c, 0x02, 0x08, 0x25, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0x25, 0x20,
	0x81, 0x62, 0xa0, 0x3a, 0x66, 0xa0, 0x3a, 0x28, 0xcf, 0x28, 0x92, 0x8b, 0x07, 0xac, 0x30, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x93, 0x8b, 0x03, 0xa6, 0x57, 0x48, 0x56, 0x0f, 0xd9,
	0x66, 0x3d, 0x34, 0x6b, 0xa5, 0xe4, 0x70, 0x49, 0x43, 0xac, 0x74, 0xe2, 0x8b, 0x82, 0xbb, 0x5c,
	0x1f, 0x88, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0xe4, 0x63, 0xfb, 0xd3, 0x00, 0x00, 0x00,
}
